### PR TITLE
Added Fonts

### PR DESCRIPTION
**Pull request by GamerGuy-52**
Added:
- JetBrains Mono
- Roboto Mono

### CODE REVIEW

**Comment by AmraniCh** [comment]
Hey, thanks for your PR.

The Google fonts links that's you added are including also italic styles, and unfortunately the italic styles are not supported by this extension (should be supported in the next versions), so please edit the links so they can include only regular styles, thank you!

**Comment by GamerGuy-52** [comment]
Your welcome! I tried the extension with the fonts I added from my fork. It worked just like charm. I get your point, but it wont affect the extension by adding italics.

**Comment by AmraniCh** [comment]
Ehmm, it works but the weights dropdown elements will be doubled and this may confuse people who use this extension.

ScreenShot_20210912162651

**Comment by GamerGuy-52** [comment]
I created a new pull request with two new fonts and I removed all the italics. Kindly check it out.

**Pull request closed without merging**
